on: [push, pull_request]

name: lint

jobs:
  lint:
    runs-on: ubuntu-18.04
    
    env:
      GITHUB_PAT: ${{ secrets.GHA_PAT }}
    
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: 'release'

      - uses: r-lib/actions/setup-r-dependencies@v1

      - name: Lint
        run: |
          out <- 
            lintr::lint_package(
              linters = lintr::with_defaults(
                object_usage_linter = NULL,
                trailing_whitespace_linter = NULL,
                cyclocomp_linter = NULL
              ),
            exclusions = c(
              list.files("tests", recursive = TRUE, full.names = TRUE),
              list.files("man", recursive = TRUE, full.names = TRUE),
              list.files("vignettes", recursive = TRUE, full.names = TRUE),
              list.files("data-raw", recursive = TRUE, full.names = TRUE)
              )
            )
          print(out)
          if (length(out)) stop("lints found")
        shell: Rscript {0}
        
